name: dev-infra

services:
  postgres:
    image: postgres:17.2-alpine3.21
    shm_size: 128mb
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testing
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  openfga-migrate:
    depends_on:
      postgres:
        condition: service_healthy
    image: openfga/openfga:v1.8.4
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:testing@postgres:5432/postgres?sslmode=disable
    command: migrate

  openfga:
    depends_on:
      openfga-migrate:
        condition: service_completed_successfully
    image: openfga/openfga:v1.8.4
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:testing@postgres:5432/postgres?sslmode=disable
      - OPENFGA_DATASTORE_MAX_OPEN_CONNS=30 # postgres allows 100 by default
    command: run
    healthcheck:
      test: [ "CMD", "/usr/local/bin/grpc_health_probe", "-addr=openfga:8081" ]
      interval: 5s
      timeout: 30s
      retries: 3
    ports:
      - "6080:8080" # http | you can use a public playground by directing it to your local openfga instance host like this https://play.fga.dev/sandbox/?fga_api_host=127.0.0.1%3A6080&fga_api_scheme=http&fga_api_token=
      - "6081:8081" # grpc
      - "6112:2112" # prometheus metrics
